[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-ra -q --strict-markers --cov=python_automation --cov-report=html --cov-report=term"
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "adobe_api: Tests requiring Adobe API access",
    "slow: Slow running tests"
]

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  node_modules
  | .git
  | .venv
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "build", "dist", "venv", "node_modules"]

[tool.bandit]
exclude_dirs = ["tests", "venv", "node_modules"]
skips = ["B101"]  # Skip assert_used test

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true