# Prometheus Configuration for Adobe Automation
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'adobe-automation'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # Adobe Automation API metrics
  - job_name: 'adobe-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'adobe-api'
          component: 'backend'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'

  # SQL Server metrics
  - job_name: 'mssql'
    static_configs:
      - targets: ['sql-exporter:9399']
        labels:
          service: 'mssql'
          component: 'database'

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'docker'
          component: 'containers'

  # Custom Adobe metrics endpoint
  - job_name: 'adobe-metrics'
    metrics_path: '/api/metrics/custom'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'adobe-custom'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'adobe_.*'
        action: keep